// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXkUfY-9WtwhsShHiGNkwANTW8DzWmTw',
    appId: '1:158761436949:android:edf32c6b99bc5797de8b1c',
    messagingSenderId: '158761436949',
    projectId: 'luoneo-bg',
    storageBucket: 'luoneo-bg.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaZsnAknERrvxVB9JcA8wtJ2AnZZnq49w',
    appId: '1:158761436949:ios:346467fde24e3e7fde8b1c',
    messagingSenderId: '158761436949',
    projectId: 'luoneo-bg',
    storageBucket: 'luoneo-bg.firebasestorage.app',
    androidClientId:
        '158761436949-7garh65lridi7ujmmdsuap05k7h9angv.apps.googleusercontent.com',
    iosClientId:
        '158761436949-ubjqu7fvvt3hkficstncb9nbtklubhqr.apps.googleusercontent.com',
    iosBundleId: 'com.luoneo.bg.provider',
  );
}
